global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'pulseguard_backend'
    static_configs:
      - targets: ['host.docker.internal:5000']
    # If on Linux, use 'localhost:5000' or your local IP instead of host.docker.internal